name: CI
on: [push]
jobs:
  build-server:
    name: Test Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd poker-server yarn install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd poker-server yarn build
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd poker-server yarn test
  build-client:
    name: Test Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd poker-client yarn install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd poker-client yarn build
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd poker-client yarn test
